FROM alpine:3.5
LABEL maintainer Evan Wilde <etcwilde@uvic.ca>
# May 05, 2017

# Add the www-data user
RUN adduser -D -H www-data
VOLUME ["/app"]

# Copy requirements
COPY req.txt /tmp/req.txt

# Install packages and dependencies
RUN apk add --no-cache python3 uwsgi-python3 py3-psycopg2 su-exec \
  && pip3 install -r /tmp/req.txt && rm -r /root/.cache/pip/*

ENV DEBUG=true
EXPOSE 5000
WORKDIR /app
CMD ["sh"]
# CMD ["su-exec", "www-data", "python3", "./run_server.py"]
